/* Phase 2 — StudentDashboard part B (attendance log + results + homework) */
module.exports = {
  'src/components/StudentDashboard.tsx': [
    { line: 1147, find: '>Attendance Log History</h1>', replace: ">{L('Attendance Log History', 'حاضری لاگ تاریخ')}</h1>" },
    { line: 1148, find: '>Evaluate cumulative presence, date stamps, and verify teacher registers.</p>', replace: ">{L('Evaluate cumulative presence, date stamps, and verify teacher registers.', 'کل حاضری، تاریخیں اور اساتذہ کے رجسٹر جانچیں۔')}</p>" },
    { line: 1154, find: '>Total Classes Conducted</span>', replace: ">{L('Total Classes Conducted', 'کل ہوئی کلاسیں')}</span>" },
    { line: 1159, find: '>Total days Attended</span>', replace: ">{L('Total days Attended', 'حاضری کے کل دن')}</span>" },
    { line: 1165, find: '>Overall Ratio</span>', replace: ">{L('Overall Ratio', 'مجموعی تناسب')}</span>" },
    { line: 1175, find: '>Attendance Log Journal</h3>', replace: ">{L('Attendance Log Journal', 'حاضری لاگ جرنال')}</h3>" },
    { line: 1182, find: '>Log Date</th>', replace: ">{L('Log Date', 'لاگ تاریخ')}</th>" },
    { line: 1183, find: '>Academic Calendar Period</th>', replace: ">{L('Academic Calendar Period', 'تعلیمی کیلنڈر مدت')}</th>" },
    { line: 1184, find: '>Status</th>', replace: ">{L('Status', 'صورتحال')}</th>" },
    { line: 1192, find: '>General Academic Session</td>', replace: ">{L('General Academic Session', 'عمومی تعلیمی سیشن')}</td>" },
    { line: 1207, find: 'No attendance records have been registered for your ID.', replace: "{L('No attendance records have been registered for your ID.', 'آپ کی آئی ڈی کی کوئی حاضری درج نہیں ہے۔')}" },
    { line: 1223, find: '>Academic Score Sheets</h1>', replace: ">{L('Academic Score Sheets', 'تعلیمی نتائج شیٹس')}</h1>" },
    { line: 1224, find: '>Review scores, max markings, automated letter grades, and subject distributions.</p>', replace: ">{L('Review scores, max markings, automated letter grades, and subject distributions.', 'نمبر، زیادہ سے زیادہ نمبر، خودکار گریڈ اور مضامین کی توزیع دیکھیں۔')}</p>" },
    { line: 1234, find: 'Academic Performance Trends', replace: "{L('Academic Performance Trends', 'تعلیمی کارکردگی کے رجحانات')}" },
    { line: 1237, find: 'Progress tracking of subject scores across unit and summative tests.', replace: "{L('Progress tracking of subject scores across unit and summative tests.', 'یونٹ اور حتمی امتحانات میں مضامین کے نمبروں کی پیش رفت۔')}" },
    { line: 1315, find: '>Subject Name</th>', replace: ">{L('Subject Name', 'مضمون کا نام')}</th>" },
    { line: 1316, find: '>Marking Scored</th>', replace: ">{L('Marking Scored', 'حاصل نمبر')}</th>" },
    { line: 1317, find: '>Percentage Scored</th>', replace: ">{L('Percentage Scored', 'حاصل فیصد')}</th>" },
    { line: 1318, find: '>Letter Grade</th>', replace: ">{L('Letter Grade', 'حروف گریڈ')}</th>" },
    { line: 1351, find: 'No score records have been logged into your student register yet.', replace: "{L('No score records have been logged into your student register yet.', 'آپ کے طلبہ رجسٹر میں ابھی کوئی نتیجہ درج نہیں ہوا۔')}" },
    { line: 1365, find: 'Homework Diary', replace: "{L('Homework Diary', 'گھر کا کام ڈائری')}" },
    { line: 1385, find: '>Your teacher has not posted any homework for this class.</p>', replace: ">{L('Your teacher has not posted any homework for this class.', 'اس کلاس کے لیے استاد نے کوئی گھر کا کام نہیں دیا۔')}</p>" },
    { line: 1407, find: 'Overdue', replace: "{L('Overdue', 'میعادگزشتہ')}" },
    { line: 1412, find: 'Due Soon', replace: "{L('Due Soon', 'جلد واجب')}" },
    { line: 1426, find: "{isOverdue ? 'Deadline Passed' : `Due: ${assn.dueDate}`}", replace: "{isOverdue ? L('Deadline Passed', 'آخری تاریخ گزر گئی') : L(`Due: ${assn.dueDate}`, `آخری تاریخ: ${assn.dueDate}`)}" },
  ],
};