/* Phase 3 — TeacherDashboard batch 5: swipe attendance, WhatsApp alerts, teacher diary */
module.exports = {
  'src/components/TeacherDashboard.tsx': [
    { line: 2541, find: "{isPaid ? 'Fee Paid' : 'Fee Pending'}", replace: "{isPaid ? L('Fee Paid', 'فیس ادا شدہ') : L('Fee Pending', 'فیس باقی')}" },
    { line: 2563, find: "{st === 'present' ? 'P' : st === 'absent' ? 'A' : st === 'late' ? 'L' : 'LV'}", replace: "{st === 'present' ? L('P', 'ح') : st === 'absent' ? L('A', 'غ') : st === 'late' ? L('L', 'ت') : L('LV', 'ر')}" },
    { line: 2574, find: "No student profiles enrolled inside the class scope.", replace: "{L('No student profiles enrolled inside the class scope.', 'اس کلاس کے دائرے میں کوئی طالب علم درج نہیں۔')}" },
    { line: 2590, find: "Commit and Save Attendance Logs", replace: "{L('Commit and Save Attendance Logs', 'حاضری کے لاگ محفوظ کریں')}" },
    { line: 2633, find: "toast.success(`Marked ${currentStudent.name} as Present`);", replace: "toast.success(L(`Marked ${currentStudent.name} as Present`, `${currentStudent.name} کو حاضر لگا دیا گیا`));" },
    { line: 2638, find: "toast.error(`Marked ${currentStudent.name} as Absent`);", replace: "toast.error(L(`Marked ${currentStudent.name} as Absent`, `${currentStudent.name} کو غیر حاضر لگا دیا گیا`));" },
    { line: 2656, find: "Roll #{currentStudent.rollNumber}", replace: "{L('Roll #', 'رول نمبر')} {currentStudent.rollNumber}" },
    { line: 2659, find: "Swipe Left (A) | Swipe Right (P)", replace: "{L('Swipe Left (A) | Swipe Right (P)', 'بائیں سوائپ (غ) | دائیں سوائپ (ح)')}" },
    { line: 2685, find: ">Or tap buttons</span>", replace: ">{L('Or tap buttons', 'یا بٹن دبائیں')}</span>" },
    { line: 2724, find: "Rewind Previous Student", replace: "{L('Rewind Previous Student', 'پچھلے طالب علم پر جائیں')}" },
    { line: 2736, find: ">All Student Cards Swiped!</h3>", replace: ">{L('All Student Cards Swiped!', 'تمام طلبہ کارڈ مکمل ہو گئے!')}</h3>" },
    { line: 2737, find: ">You have reviewed all student attendance records for this date.</p>", replace: ">{L('You have reviewed all student attendance records for this date.', 'آپ اس تاریخ کے تمام طلبہ کے حاضری ریکارڈ دیکھ چکے ہیں۔')}</p>" },
    { line: 2743, find: ">Present</p>", replace: ">{L('Present', 'حاضر')}</p>" },
    { line: 2749, find: ">Absent</p>", replace: ">{L('Absent', 'غیر حاضر')}</p>" },
    { line: 2775, find: ">No students in this class.</div>", replace: ">{L('No students in this class.', 'اس کلاس میں کوئی طالب علم نہیں۔')}</div>" },
    { line: 2788, find: "📢 WhatsApp Absent Alert Center", replace: "📢 {L('WhatsApp Absent Alert Center', 'واٹس ایپ غیر حاضری الرٹ سینٹر')}" },
    { line: 2791, find: "Prowl through absent registers on active date {attendanceDate} and execute direct manual alerts or auto rule models to parent contacts.", replace: "{L('Prowl through absent registers on active date', 'منتخب تاریخ')} {attendanceDate} {L('and execute direct manual alerts or auto rule models to parent contacts.', 'کی غیر حاضری دیکھیں اور والدین کو دستی یا خودکار الرٹ بھیجیں۔')}" },
    { line: 2796, find: ">Read-Only View</span>", replace: ">{L('Read-Only View', 'صرف دیکھنے کی اجازت')}</span>" },
    { line: 2797, find: ">Absence alerts must be approved and dispatched by the school coordinator.</p>", replace: ">{L('Absence alerts must be approved and dispatched by the school coordinator.', 'غیر حاضری کے الرٹ اسکول کارڈینیٹر کی منظوری سے بھیجے جاتے ہیں۔')}</p>" },
    { line: 2809, find: "Roll: #{st.rollNumber}", replace: "{L('Roll', 'رول')}: #{st.rollNumber}" },
    { line: 2812, find: ">Parent Name</p>", replace: ">{L('Parent Name', 'والد کا نام')}</p>" },
    { line: 2813, find: "{st.guardianName || 'Guardian'}", replace: "{st.guardianName || L('Guardian', 'والدین')}" },
    { line: 2821, find: "★ Perfect Attendance Record for {viewClass?.className || 'Class Group'} on Date {attendanceDate}! No Parent pings necessary.", replace: "★ {L('Perfect Attendance Record for', 'مکمل حاضری ریکارڈ —')} {viewClass?.className || L('Class Group', 'کلاس گروپ')} {L('on Date', 'بتاریخ')} {attendanceDate}! {L('No Parent pings necessary.', 'والدین کو اطلاع دینے کی ضرورت نہیں۔')}" },
    { line: 2839, find: "Teacher Diary & Assignments", replace: "{L('Teacher Diary & Assignments', 'استاد ڈائری و ہوم ورک')}" },
    { line: 2856, find: ">Post New Assignment</h3>", replace: ">{L('Post New Assignment', 'نیا ہوم ورک لگائیں')}</h3>" },
    { line: 2861, find: ">Class</label>", replace: ">{L('Class', 'کلاس')}</label>" },
    { line: 2867, find: ">No assigned classes</option>", replace: ">{L('No assigned classes', 'کوئی تفویض شدہ کلاس نہیں')}</option>" },
    { line: 2875, find: ">Subject</label>", replace: ">{L('Subject', 'مضمون')}</label>" },
    { line: 2878, find: "|| 'e.g. Mathematics'}", replace: "|| L('e.g. Mathematics', 'مثلاً ریاضی')}" },
    { line: 2886, find: ">Due Date</label>", replace: ">{L('Due Date', 'آخری تاریخ')}</label>" },
    { line: 2896, find: ">Assignment Title *</label>", replace: ">{L('Assignment Title *', 'ہوم ورک کا عنوان *')}</label>" },
    { line: 2899, find: "placeholder=\"e.g. Chapter 5 Exercise Questions\"", replace: "placeholder={L('e.g. Chapter 5 Exercise Questions', 'مثلاً باب 5 کے مشقی سوالات')}" },
    { line: 2908, find: ">Instructions / Details</label>", replace: ">{L('Instructions / Details', 'ہدایات / تفصیل')}</label>" },
    { line: 2911, find: "placeholder=\"Write the assignment details, page numbers, or submission instructions here...\"", replace: "placeholder={L('Write the assignment details, page numbers, or submission instructions here...', 'یہاں ہوم ورک کی تفصیل، صفحہ نمبر یا جمع کرانے کی ہدایات لکھیں...')}" },
    { line: 2930, find: "My Posted Assignments", replace: "{L('My Posted Assignments', 'میرے لگائے گئے ہوم ورک')}" },
    { line: 2937, find: ">No assignments posted yet</p>", replace: ">{L('No assignments posted yet', 'ابھی کوئی ہوم ورک نہیں لگایا گیا')}</p>" },
    { line: 2938, find: ">Use the form above to publish homework to your class.</p>", replace: ">{L('Use the form above to publish homework to your class.', 'اپنی کلاس کو ہوم ورک دینے کے لیے اوپر کا فارم استعمال کریں۔')}</p>" },
    { line: 2966, find: "title=\"Delete assignment\"", replace: "title={L('Delete assignment', 'ہوم ورک حذف کریں')}" },
    { line: 2973, find: "{isOverdue ? 'Overdue' : `Due: ${assn.dueDate}`}", replace: "{isOverdue ? L('Overdue', 'تاریخ گزر گئی') : `${L('Due', 'آخری تاریخ')}: ${assn.dueDate}`}" },
    { line: 2976, find: "Posted {assn.createdAt ? new Date(assn.createdAt).toLocaleDateString() : ''}", replace: "{L('Posted', 'لگایا گیا')} {assn.createdAt ? new Date(assn.createdAt).toLocaleDateString() : ''}" },
  ],
};
