/* Phase 1 batch — LandingPage.tsx part 2b (inquiry form + footer) */
module.exports = {
  'src/components/LandingPage.tsx': [
    { line: 533, find: '>Digital Inquiry Portal</h3>', replace: ">{L('Digital Inquiry Portal', 'ڈیجیٹل استفسار پورٹل')}</h3>" },
    { line: 534, find: '>Registration & Information Request</p>', replace: ">{L('Registration & Information Request', 'رجسٹریشن اور معلومات کی درخواست')}</p>" },
    { line: 547, find: '>Inquiry Received</h4>', replace: ">{L('Inquiry Received', 'استفسار موصول ہوا')}</h4>" },
    { line: 549, find: 'Thank you for your interest. Our admissions counselor will contact you shortly to guide you through the enrollment matrix.', replace: "{L('Thank you for your interest. Our admissions counselor will contact you shortly to guide you through the enrollment matrix.', 'آپ کی دلچسپی کا شکریہ۔ ہمارا داخلہ کاؤنسلر جلد آپ سے رابطہ کرے گا اور داخلے کے طریقے میں رہنمائی دے گا۔')}" },
    { line: 557, find: '>Student Complete Name</label>', replace: ">{L('Student Complete Name', 'طلب علم کا پورا نام')}</label>" },
    { line: 568, find: '>Parent Contact Index</label>', replace: ">{L('Parent Contact Index', 'والدین کا رابطہ نمبر')}</label>" },
    { line: 581, find: '>Admission Grade</label>', replace: ">{L('Admission Grade', 'داخلے کی جماعت')}</label>" },
    { line: 587, find: '>Kindergarten / Prep</option>', replace: ">{L('Kindergarten / Prep', 'کِنڈر گارٹن / تیاری')}</option>" },
    { line: 588, find: '>Primary (1 - 5)</option>', replace: ">{L('Primary (1 - 5)', 'پرائمری (1 - 5)')}</option>" },
    { line: 589, find: '>Middle (6 - 8)</option>', replace: ">{L('Middle (6 - 8)', 'مڈل (6 - 8)')}</option>" },
    { line: 590, find: '>Secondary (9 - 10)</option>', replace: ">{L('Secondary (9 - 10)', 'ثانوی (9 - 10)')}</option>" },
    { line: 591, find: '>Evening Academy</option>', replace: ">{L('Evening Academy', 'شام کا اکیڈمی')}</option>" },
    { line: 596, find: '>Additional Requirements</label>', replace: ">{L('Additional Requirements', 'اضافی ضروریات')}</label>" },
    { line: 599, find: 'placeholder="Specify custom requirements or subject preferences..."', replace: "placeholder={L('Specify custom requirements or subject preferences...', 'اپنی ضروریات یا مضمون ترجیحات بتائیں…')}" },
    { line: 612, find: 'Process Inquiry', replace: "{L('Process Inquiry', 'استفسار جمع کریں')}" },
    { line: 633, find: 'Developing Scholars, Creating Legacies since 2012. We are committed to nurturing the next generation of global citizens.', replace: "{L('Developing Scholars, Creating Legacies since 2012. We are committed to nurturing the next generation of global citizens.', '2012 سے طلبہ تیار کر رہے ہیں، ورثے گڑھ رہے ہیں — ہم اگلی نسل کے پرورش کے لیے پرعزم ہیں۔')}" },
    { line: 638, find: '>Navigation</h5>', replace: ">{L('Navigation', 'ہدایت')}</h5>" },
    { line: 640, find: '>Home Campus</button>', replace: ">{L('Home Campus', 'ہوم کیمپس')}</button>" },
    { line: 641, find: '>Curriculum</button>', replace: ">{L('Curriculum', 'نصاب')}</button>" },
    { line: 642, find: '>Faculty</button>', replace: ">{L('Faculty', 'اساتذہ')}</button>" },
    { line: 643, find: '>Enrolment</button>', replace: ">{L('Enrolment', 'داخلہ')}</button>" },
    { line: 648, find: '>Portals</h5>', replace: ">{L('Portals', 'پورٹل')}</h5>" },
    { line: 650, find: '>Principal Dashboard</button>', replace: ">{L('Principal Dashboard', 'پرنسپل ڈیش بورڈ')}</button>" },
    { line: 651, find: '>Faculty Portal</button>', replace: ">{L('Faculty Portal', 'اساتذہ پورٹل')}</button>" },
    { line: 652, find: '>Student Campus</button>', replace: ">{L('Student Campus', 'طلبہ کیمپس')}</button>" },
    { line: 657, find: '>Connect</h5>', replace: ">{L('Connect', 'رابطہ')}</h5>" },
    { line: 670, find: '© 2012-2026 Principal Campus Management Center.', replace: "{L('© 2012-2026 Principal Campus Management Center.', '© 2012-2026 پرنسپل کیمپس مینجمنٹ سینٹر')}" },
    { line: 673, find: '>Privacy</a>', replace: ">{L('Privacy', 'رازداری')}</a>" },
    { line: 674, find: '>Terms</a>', replace: ">{L('Terms', 'شرائط')}</a>" },
  ],
};