/* Phase 3 — TeacherDashboard batch 8: result card preview, marks entry cards */
module.exports = {
  'src/components/TeacherDashboard.tsx': [
    { line: 3656, find: ">Result Card</h3>", replace: ">{L('Result Card', 'رزلٹ کارڈ')}</h3>" },
    { line: 3657, find: "{reportExamName.trim() || 'General Assessment'}", replace: "{reportExamName.trim() || L('General Assessment', 'عمومی جانچ')}" },
    { line: 3660, find: ">Overall</p>", replace: ">{L('Overall', 'مجموعی')}</p>" },
    { line: 3667, find: ">Subject</th>", replace: ">{L('Subject', 'مضمون')}</th>" },
    { line: 3668, find: ">Reference</th>", replace: ">{L('Reference', 'حوالہ')}</th>" },
    { line: 3669, find: ">Marks</th>", replace: ">{L('Marks', 'نمبر')}</th>" },
    { line: 3670, find: ">Percentage</th>", replace: ">{L('Percentage', 'فیصد')}</th>" },
    { line: 3692, find: ">Total</td>", replace: ">{L('Total', 'کل')}</td>" },
    { line: 3699, find: "{overallPct >= 40 ? 'PASS' : 'RE-STUDY'}", replace: "{overallPct >= 40 ? L('PASS', 'کامیاب') : L('RE-STUDY', 'دوبارہ پڑھائی')}" },
    { line: 3700, find: ">Generated from entered marks</span>", replace: ">{L('Generated from entered marks', 'درج شدہ نمبروں سے تیار شدہ')}</span>" },
    { line: 3712, find: ">No Student Selected</h3>", replace: ">{L('No Student Selected', 'کوئی طالب علم منتخب نہیں')}</h3>" },
    { line: 3714, find: "Please select a class and then choose a student from the dropdown above to begin building their multi-subject report card.", replace: "{L('Please select a class and then choose a student from the dropdown above to begin building their multi-subject report card.', 'پہلے کلاس منتخب کریں اور پھر اوپر کی فہرست سے طالب علم چنیں تاکہ کثیر المضمون رپورٹ کارڈ بنایا جا سکے۔')}" },
    { line: 3723, find: ">Exam / Test Marks Entry</h1>", replace: ">{L('Exam / Test Marks Entry', 'امتحان / ٹیسٹ نمبر اندراج')}</h1>" },
    { line: 3724, find: "First add the exam/test name and its subjects, then click a student to enter their marks for that complete test.", replace: "{L('First add the exam/test name and its subjects, then click a student to enter their marks for that complete test.', 'پہلے امتحان / ٹیسٹ کا نام اور اس کے مضامین شامل کریں، پھر نمبر درج کرنے کے لیے کسی طالب علم پر کلک کریں۔')}" },
    { line: 3730, find: ">Select Class</label>", replace: ">{L('Select Class', 'کلاس منتخب کریں')}</label>" },
    { line: 3736, find: ">-- Choose Class --</option>", replace: ">{L('-- Choose Class --', '-- کلاس منتخب کریں --')}</option>" },
    { line: 3743, find: ">Exam / Test Name</label>", replace: ">{L('Exam / Test Name', 'امتحان / ٹیسٹ کا نام')}</label>" },
    { line: 3748, find: "placeholder=\"e.g. 1st Term 2025 / Weekly Test 3\"", replace: "placeholder={L('e.g. 1st Term 2025 / Weekly Test 3', 'مثلاً پہلی ششماہی 2025 / ہفتہ وار ٹیسٹ 3')}" },
    { line: 3760, find: ">Saved Tests / Exams</h3>", replace: ">{L('Saved Tests / Exams', 'محفوظ ٹیسٹ / امتحانات')}</h3>" },
    { line: 3762, find: ">Click to open &amp; view marks</span>", replace: ">{L('Click to open & view marks', 'نمبر دیکھنے کے لیے کلک کریں')}</span>" },
    { line: 3771, find: ">No saved tests yet for this class. Create one above.</p>", replace: ">{L('No saved tests yet for this class. Create one above.', 'اس کلاس کے لیے ابھی کوئی محفوظ ٹیسٹ نہیں۔ اوپر نیا بنائیں۔')}</p>" },
    { line: 3785, find: "toast.success('Opened saved test: ' + tn);", replace: "toast.success(L('Opened saved test: ', 'محفوظ ٹیسٹ کھل گیا: ') + tn);" },
    { line: 3806, find: ">Subject</label>", replace: ">{L('Subject', 'مضمون')}</label>" },
    { line: 3809, find: ">Select Subject</option>", replace: ">{L('Select Subject', 'مضمون منتخب کریں')}</option>" },
    { line: 3818, find: ">➕ Manual Subject...</option>", replace: ">{L('➕ Manual Subject...', '➕ نیا مضمون...')}</option>" },
    { line: 3822, find: "placeholder=\"Type subject name\"", replace: "placeholder={L('Type subject name', 'مضمون کا نام لکھیں')}" },
    { line: 3828, find: ">Total Marks</label>", replace: ">{L('Total Marks', 'کل نمبر')}</label>" },
    { line: 3834, find: "toast.error('Please enter a subject'); return; }", replace: "toast.error(L('Please enter a subject', 'مضمون لکھیں')); return; }" },
    { line: 3835, find: "toast.error('Enter total marks'); return; }", replace: "toast.error(L('Enter total marks', 'کل نمبر لکھیں')); return; }" },
    { line: 3838, find: "toast.success('Subject added to test');", replace: "toast.success(L('Subject added to test', 'مضمون ٹیسٹ میں شامل ہو گیا'));" },
    { line: 3839, find: "<Plus size={14} /> Add Subject", replace: "<Plus size={14} /> {L('Add Subject', 'مضمون شامل کریں')}" },
    { line: 3859, find: ">Define the test first</h3>", replace: ">{L('Define the test first', 'پہلے ٹیسٹ کی تفصیل بنائیں')}</h3>" },
    { line: 3860, find: "Add the exam/test name and at least one subject above, then choose a student to enter marks.", replace: "{L('Add the exam/test name and at least one subject above, then choose a student to enter marks.', 'اوپر امتحان / ٹیسٹ کا نام اور کم از کم ایک مضمون شامل کریں، پھر نمبر درج کرنے کے لیے طالب علم چنیں۔')}" },
    { line: 3867, find: "toast.error('Select a student'); return; }", replace: "toast.error(L('Select a student', 'طالب علم منتخب کریں')); return; }" },
    { line: 3882, find: "toast.success(`Saved ${examN} for ${student.name}`);", replace: "toast.success(L(`Saved ${examN} for ${student.name}`, `${examN} — ${student.name} کے نمبر محفوظ ہو گئے`));" },
    { line: 3886, find: "toast.error('Select a student'); return; }", replace: "toast.error(L('Select a student', 'طالب علم منتخب کریں')); return; }" },
    { line: 3903, find: "<title>Result Card - ${st.name}</title>", replace: "<title>${L('Result Card', 'رزلٹ کارڈ')} - ${st.name}</title>" },
    { line: 3925, find: "${examN} · Roll #${st.rollNumber}", replace: "${examN} · ${L('Roll #', 'رول نمبر')}${st.rollNumber}" },
    { line: 3926, find: ">Overall</div>", replace: ">${L('Overall', 'مجموعی')}</div>" },
    { line: 3926, find: "${pct >= 40 ? 'PASS' : 'RE-STUDY'}", replace: "${pct >= 40 ? L('PASS', 'کامیاب') : L('RE-STUDY', 'دوبارہ پڑھائی')}" },
    { line: 3928, find: "><b>Class</b>", replace: "><b>${L('Class', 'کلاس')}</b>" },
    { line: 3928, find: "><b>Roll Number</b>", replace: "><b>${L('Roll Number', 'رول نمبر')}</b>" },
    { line: 3928, find: "><b>Total</b>", replace: "><b>${L('Total', 'کل')}</b>" },
    { line: 3930, find: "<th>Subject</th>", replace: "<th>${L('Subject', 'مضمون')}</th>" },
    { line: 3930, find: ">Marks</th>", replace: ">${L('Marks', 'نمبر')}</th>" },
    { line: 3930, find: ">Percentage</th>", replace: ">${L('Percentage', 'فیصد')}</th>" },
    { line: 3932, find: ">Total Percentage</td>", replace: ">${L('Total Percentage', 'کل فیصد')}</td>" },
    { line: 3934, find: "— Result Card</span>", replace: "— ${L('Result Card', 'رزلٹ کارڈ')}</span>" },
    { line: 3934, find: "<span>Date: ${new Date().toLocaleDateString()}", replace: "<span>${L('Date', 'تاریخ')}: ${new Date().toLocaleDateString()}" },
    { line: 3939, find: "toast.error('Pop-up blocked. Allow pop-ups to print.'); return; }", replace: "toast.error(L('Pop-up blocked. Allow pop-ups to print.', 'پاپ اپ بلاک ہو گیا۔ پرنٹ کرنے کے لیے پاپ اپ کی اجازت دیں۔')); return; }" },
    { line: 3954, find: ">Entering: {examN}</p>", replace: ">{L('Entering', 'اندراج')}: {examN}</p>" },
    { line: 3956, find: ">Roll #{student.rollNumber}", replace: ">{L('Roll #', 'رول نمبر')} {student.rollNumber}" },
    { line: 3958, find: "Back to Students", replace: "{L('Back to Students', 'طلبہ پر واپس')}" },
    { line: 3966, find: ">Subject</th>", replace: ">{L('Subject', 'مضمون')}</th>" },
    { line: 3967, find: ">Total Marks</th>", replace: ">{L('Total Marks', 'کل نمبر')}</th>" },
    { line: 3968, find: ">Obtained Marks</th>", replace: ">{L('Obtained Marks', 'حاصل کردہ نمبر')}</th>" },
    { line: 3996, find: ">Total: <span className=\"text-teal-700 text-sm\">", replace: ">{L('Total', 'کل')}: <span className=\"text-teal-700 text-sm\">" },
    { line: 3996, find: "{pct >= 40 ? 'PASS' : 'RE-STUDY'}", replace: "{pct >= 40 ? L('PASS', 'کامیاب') : L('RE-STUDY', 'دوبارہ پڑھائی')}" },
    { line: 3997, find: "<Printer size={14} /> Print</button>", replace: "<Printer size={14} /> {L('Print', 'پرنٹ')}</button>" },
    { line: 3998, find: "<Save size={14} /> Save Test</button>", replace: "<Save size={14} /> {L('Save Test', 'ٹیسٹ محفوظ کریں')}</button>" },
    { line: 4006, find: ">Result Card</h3>", replace: ">{L('Result Card', 'رزلٹ کارڈ')}</h3>" },
    { line: 4010, find: ">Overall</p>", replace: ">{L('Overall', 'مجموعی')}</p>" },
    { line: 4017, find: ">Subject</th>", replace: ">{L('Subject', 'مضمون')}</th>" },
    { line: 4018, find: ">Marks</th>", replace: ">{L('Marks', 'نمبر')}</th>" },
    { line: 4019, find: ">Percentage</th>", replace: ">{L('Percentage', 'فیصد')}</th>" },
    { line: 4036, find: ">Total</td>", replace: ">{L('Total', 'کل')}</td>" },
    { line: 4050, find: "} Pupils</span>", replace: "} {L('Pupils', 'طلبہ')}</span>" },
    { line: 4069, find: "Roll #{st.rollNumber}", replace: "{L('Roll #', 'رول نمبر')} {st.rollNumber}" },
    { line: 4071, find: ">SAVED</span>", replace: ">{L('SAVED', 'محفوظ')}</span>" },
    { line: 4082, find: ">No Class Selected</h3>", replace: ">{L('No Class Selected', 'کوئی کلاس منتخب نہیں')}</h3>" },
    { line: 4083, find: ">Select a class above to see its students.</p>", replace: ">{L('Select a class above to see its students.', 'طلبہ دیکھنے کے لیے اوپر سے کلاس منتخب کریں۔')}</p>" },
    { line: 4096, find: ">Class Schedule Overview</h1>", replace: ">{L('Class Schedule Overview', 'کلاس شیڈول کا جائزہ')}</h1>" },
  ],
};
