/* Phase 3 — TeacherDashboard batch 3: header, notification dropdown, home cards, password modal */
module.exports = {
  'src/components/TeacherDashboard.tsx': [
    { line: 1391, find: "aria-label=\"Close menu\"", replace: "aria-label={L('Close menu', 'مینو بند کریں')}" },
    { line: 1544, find: "No Active Lecture Right Now", replace: "{L('No Active Lecture Right Now', 'ابھی کوئی لیکچر جاری نہیں')}" },
    { line: 1554, find: "LIVE: {currentPeriodObj.period}", replace: "{L('LIVE', 'جاری')}: {currentPeriodObj.period}" },
    { line: 1554, find: "— Class {classLabel})", replace: "— {L('Class', 'کلاس')} {classLabel})" },
    { line: 1565, find: "title=\"Test class bells and push notifications\"", replace: "title={L('Test class bells and push notifications', 'کلاس بیل اور پش اطلاعات آزمائیں')}" },
    { line: 1576, find: "title=\"Toggle Dark/Light Mode\"", replace: "title={L('Toggle Dark/Light Mode', 'ڈارک / لائٹ موڈ بدلیں')}" },
    { line: 1589, find: "title=\"Notifications\"", replace: "title={L('Notifications', 'اطلاعات')}" },
    { line: 1610, find: ">School Bells / Alerts</span>", replace: ">{L('School Bells / Alerts', 'اسکول بیل / اطلاعات')}</span>" },
    { line: 1613, find: ">Mark Read</button>", replace: ">{L('Mark Read', 'پڑھ لیں')}</button>" },
    { line: 1618, find: ">Clear</button>", replace: ">{L('Clear', 'صاف کریں')}</button>" },
    { line: 1625, find: "No notifications received yet", replace: "{L('No notifications received yet', 'ابھی کوئی اطلاع نہیں آئی')}" },
    { line: 1753, find: "Class Lectures scheduled today ({todayClasses.length})", replace: "{L('Class Lectures scheduled today', 'آج کے طے شدہ کلاس لیکچرز')} ({todayClasses.length})" },
    { line: 1755, find: ">Timetabled Lectures</span>", replace: ">{L('Timetabled Lectures', 'ٹائم ٹیبل کے لیکچرز')}</span>" },
    { line: 1760, find: "☕ No formal lectures assigned to your ID under <strong>{currentDayName}</strong>.", replace: "☕ {L('No formal lectures assigned to your ID under', 'آپ کی آئی ڈی کے لیے کوئی باقاعدہ لیکچر نہیں')} <strong>{currentDayName}</strong>." },
    { line: 1761, find: ">Great opportunity to review grading portfolios or coordinate with fellow faculty members!</p>", replace: ">{L('Great opportunity to review grading portfolios or coordinate with fellow faculty members!', 'یہ بہترین موقع ہے کہ گریڈنگ پورٹ فولیو دیکھیں یا ساتھی اساتذہ سے رابطہ کریں!')}</p>" },
    { line: 1781, find: "Primary Mentor", replace: "{L('Primary Mentor', 'پرائمری منٹور')}" },
    { line: 1786, find: "Subject: <span className=\"text-teal-900\">{lecture.subject}</span>", replace: "{L('Subject', 'مضمون')}: <span className=\"text-teal-900\">{lecture.subject}</span>" },
    { line: 1808, find: "Today's Attendance Checklist ({attendanceStatusList.length})", replace: "{L(\"Today's Attendance Checklist\", 'آج کی حاضری چیک لسٹ')} ({attendanceStatusList.length})" },
    { line: 1813, find: ">Total P: {attendanceStatusList.reduce", replace: ">{L('Total P', 'کل حاضر')}: {attendanceStatusList.reduce" },
    { line: 1817, find: ">Total A: {attendanceStatusList.reduce", replace: ">{L('Total A', 'کل غیر حاضر')}: {attendanceStatusList.reduce" },
    { line: 1819, find: ">Verification Task</span>", replace: ">{L('Verification Task', 'تصدیقی کام')}</span>" },
    { line: 1825, find: "No assigned classroom cohorts requiring registers today.", replace: "{L('No assigned classroom cohorts requiring registers today.', 'آج کوئی تفویض شدہ کلاس رجسٹر درکار نہیں۔')}" },
    { line: 1841, find: "Class {item.className}", replace: "{L('Class', 'کلاس')} {item.className}" },
    { line: 1845, find: "My Cohort", replace: "{L('My Cohort', 'میرا گروپ')}" },
    { line: 1850, find: "Total Pupils: <span className=\"font-bold text-slate-700\">{item.studentCount}</span>", replace: "{L('Total Pupils', 'کل طلبہ')}: <span className=\"font-bold text-slate-700\">{item.studentCount}</span>" },
    { line: 1854, find: "<span className=\"text-amber-600 font-bold\">P: {item.presentCount}</span>", replace: "<span className=\"text-amber-600 font-bold\">{L('P', 'ح')}: {item.presentCount}</span>" },
    { line: 1856, find: "<span className=\"text-rose-600 font-bold\">A: {item.absentCount}</span>", replace: "<span className=\"text-rose-600 font-bold\">{L('A', 'غ')}: {item.absentCount}</span>" },
    { line: 1865, find: "✓ Logged", replace: "✓ {L('Logged', 'درج')}" },
    { line: 1886, find: "{item.marked ? 'Re-edit' : 'Take Attendance'}", replace: "{item.marked ? L('Re-edit', 'دوبارہ ترمیم') : L('Take Attendance', 'حاضری لگائیں')}" },
    { line: 1897, find: "Remainder: Principal office sync expects all student attendance records to be updated and signed by 2:00 PM today.", replace: "{L('Remainder: Principal office sync expects all student attendance records to be updated and signed by 2:00 PM today.', 'یاد دہانی: پرنسپل آفس کے مطابق تمام طلبہ کی حاضری آج 2:00 بجے تک اپ ڈیٹ اور تصدیق شدہ ہونی چاہیے۔')}" },
    { line: 1912, find: ">My Timetable</h2>", replace: ">{L('My Timetable', 'میرا ٹائم ٹیبل')}</h2>" },
    { line: 1913, find: ">Select a day to view its schedule</p>", replace: ">{L('Select a day to view its schedule', 'شیڈول دیکھنے کے لیے دن منتخب کریں')}</p>" },
    { line: 1920, find: ">Day:</span>", replace: ">{L('Day', 'دن')}:</span>" },
    { line: 1933, find: "{day === 'all' ? 'All Days' : day}", replace: "{day === 'all' ? L('All Days', 'تمام دن') : day}" },
    { line: 1975, find: ">No sessions assigned in global timetable yet.</p>", replace: ">{L('No sessions assigned in global timetable yet.', 'عالمی ٹائم ٹیبل میں ابھی کوئی سیشن تفویض نہیں ہوا۔')}</p>" },
    { line: 1992, find: ">Mark Attendance</h3>", replace: ">{L('Mark Attendance', 'حاضری لگائیں')}</h3>" },
    { line: 1993, find: ">Log present or absent indices for pupils on a selected calendar day.</p>", replace: ">{L('Log present or absent indices for pupils on a selected calendar day.', 'منتخب تاریخ پر طلبہ کی حاضری یا غیر حاضری درج کریں۔')}</p>" },
    { line: 2006, find: ">Configure Scores</h3>", replace: ">{L('Configure Scores', 'نمبر ترتیب دیں')}</h3>" },
    { line: 2007, find: ">Commend academic marks for Unit Tests, Mid-Year cycle, and Final exams.</p>", replace: ">{L('Commend academic marks for Unit Tests, Mid-Year cycle, and Final exams.', 'یونٹ ٹیسٹ، ششماہی اور سالانہ امتحانات کے تعلیمی نمبر درج کریں۔')}</p>" },
    { line: 2034, find: ">Update Credentials</h2>", replace: ">{L('Update Credentials', 'لاگ اِن تفصیلات اپ ڈیٹ کریں')}</h2>" },
    { line: 2035, find: ">Portal Access Security</p>", replace: ">{L('Portal Access Security', 'پورٹل رسائی سیکیورٹی')}</p>" },
    { line: 2042, find: ">Current ID</label>", replace: ">{L('Current ID', 'موجودہ آئی ڈی')}</label>" },
    { line: 2051, find: ">New Password</label>", replace: ">{L('New Password', 'نیا پاس ورڈ')}</label>" },
    { line: 2059, find: ">Minimum 8 characters recommended for robust security.</p>", replace: ">{L('Minimum 8 characters recommended for robust security.', 'مضبوط سیکیورٹی کے لیے کم از کم 8 حروف تجویز کیے جاتے ہیں۔')}</p>" },
    { line: 2065, find: "toast.error('Password must be at least 4 characters long.');", replace: "toast.error(L('Password must be at least 4 characters long.', 'پاس ورڈ کم از کم 4 حروف کا ہونا چاہیے۔'));" },
    { line: 2074, find: "toast.success('Password updated successfully! Next login requires new credentials.');", replace: "toast.success(L('Password updated successfully! Next login requires new credentials.', 'پاس ورڈ کامیابی سے اپ ڈیٹ ہو گیا! اگلی بار نئی تفصیلات سے لاگ اِن کریں۔'));" },
    { line: 2079, find: "Commit Changes", replace: "{L('Commit Changes', 'تبدیلیاں محفوظ کریں')}" },
    { line: 2092, find: "You are editing simulated data. This app uses <strong>Indexed Storage (localStorage)</strong>. You can safely simulate different dates, record marks, and re-login as a student to see the changes update in real time.", replace: "{L('You are editing simulated data. This app uses', 'آپ نقلی ڈیٹا میں ترمیم کر رہے ہیں۔ یہ ایپ استعمال کرتی ہے')} <strong>{L('Indexed Storage (localStorage)', 'انڈیکسڈ اسٹوریج (لوکل اسٹوریج)')}</strong>{L('. You can safely simulate different dates, record marks, and re-login as a student to see the changes update in real time.', '۔ آپ مختلف تاریخیں آزما سکتے ہیں، نمبر درج کر سکتے ہیں اور طالب علم کے طور پر دوبارہ لاگ اِن کر کے تبدیلیاں فوراً دیکھ سکتے ہیں۔')}" },
  ],
};
