/* Phase 3 — TeacherDashboard batch 12: student profile modal + receipt dispatch modal + security notice */
module.exports = {
  'src/components/TeacherDashboard.tsx': [
    { line: 4841, find: "Once you change your ID or Password, you must use the new credentials for your next login session. These settings are tracked by the Digital Registrar Office (Principal Dashboard) for administrative security protocols.", replace: "{L('Once you change your ID or Password, you must use the new credentials for your next login session. These settings are tracked by the Digital Registrar Office (Principal Dashboard) for administrative security protocols.', 'آئی ڈی یا پاس ورڈ تبدیل کرنے کے بعد اگلی لاگ اِن میں نئی تفصیلات استعمال کرنا ضروری ہے۔ یہ ترتیبات انتظامی سیکیورٹی کے لیے ڈیجیٹل رجسٹرار آفس (پرنسپل ڈیش بورڈ) میں محفوظ رہتی ہیں۔')}" },
    { line: 4985, find: ">Student Bio</h3>", replace: ">{L('Student Bio', 'طالب علم کا تعارف')}</h3>" },
    { line: 4988, find: ">Academic Email</p>", replace: ">{L('Academic Email', 'تعلیمی ای میل')}</p>" },
    { line: 4992, find: ">Username</p>", replace: ">{L('Username', 'صارف نام')}</p>" },
    { line: 4999, find: ">Guardian Context</h3>", replace: ">{L('Guardian Context', 'والدین کی تفصیل')}</h3>" },
    { line: 5002, find: ">Parent Phone</p>", replace: ">{L('Parent Phone', 'والدین کا فون')}</p>" },
    { line: 5006, find: ">Guardian Name</p>", replace: ">{L('Guardian Name', 'والد / سرپرست کا نام')}</p>" },
    { line: 5013, find: ">Financial Status</h3>", replace: ">{L('Financial Status', 'مالی صورتحال')}</h3>" },
    { line: 5015, find: ">Monthly Base Fee</p>", replace: ">{L('Monthly Base Fee', 'ماہانہ بنیادی فیس')}</p>" },
    { line: 5027, find: ">Direct Mark Management</h3>", replace: ">{L('Direct Mark Management', 'براہِ راست نمبروں کا انتظام')}</h3>" },
    { line: 5033, find: ">Subject</label>", replace: ">{L('Subject', 'مضمون')}</label>" },
    { line: 5042, find: ">Max Marks</label>", replace: ">{L('Max Marks', 'زیادہ سے زیادہ نمبر')}</label>" },
    { line: 5053, find: ">Test / Assignment Title</label>", replace: ">{L('Test / Assignment Title', 'ٹیسٹ / ہوم ورک کا عنوان')}</label>" },
    { line: 5058, find: "placeholder=\"e.g. Monthly Test, Assignment 1\"", replace: "placeholder={L('e.g. Monthly Test, Assignment 1', 'مثلاً ماہانہ ٹیسٹ، ہوم ورک 1')}" },
    { line: 5064, find: ">Marks Obtained</label>", replace: ">{L('Marks Obtained', 'حاصل کردہ نمبر')}</label>" },
    { line: 5070, find: "placeholder=\"Score\"", replace: "placeholder={L('Score', 'نمبر')}" },
    { line: 5081, find: "Commit Mark to Record", replace: "{L('Commit Mark to Record', 'نمبر ریکارڈ میں محفوظ کریں')}" },
    { line: 5089, find: ">Academic History</h3>", replace: ">{L('Academic History', 'تعلیمی تاریخ')}</h3>" },
    { line: 5090, find: ">Latest Entries</span>", replace: ">{L('Latest Entries', 'تازہ اندراجات')}</span>" },
    { line: 5115, find: ">No academic records found</p>", replace: ">{L('No academic records found', 'کوئی تعلیمی ریکارڈ نہیں ملا')}</p>" },
    { line: 5128, find: "Close Profile", replace: "{L('Close Profile', 'پروفائل بند کریں')}" },
    { line: 5147, find: ">Receipt Dispatch</h3>", replace: ">{L('Receipt Dispatch', 'رسید ارسال')}</h3>" },
    { line: 5152, find: "title=\"Close window\"", replace: "title={L('Close window', 'ونڈو بند کریں')}" },
    { line: 5161, find: ">Recipient Parent</p>", replace: ">{L('Recipient Parent', 'وصول کنندہ والدین')}</p>" },
    { line: 5165, find: ">Phone Number</p>", replace: ">{L('Phone Number', 'فون نمبر')}</p>" },
    { line: 5171, find: ">Message Content</label>", replace: ">{L('Message Content', 'پیغام کا متن')}</label>" },
    { line: 5188, find: "toast.success(\"Copied to clipboard\");", replace: "toast.success(L('Copied to clipboard', 'کلپ بورڈ میں کاپی ہو گیا'));" },
    { line: 5192, find: "Copy Text", replace: "{L('Copy Text', 'متن کاپی کریں')}" },
    { line: 5203, find: "Dismiss", replace: "{L('Dismiss', 'بند کریں')}" },
  ],
};
