/* Phase 2 — StudentDashboard part A (toasts, header, notifications, gauge) */
module.exports = {
  'src/components/StudentDashboard.tsx': [
    { line: 212, find: "toast.success(nextVal ? \"🌙 Dark theme ho gya!\" : \"☀️ Light theme ho gya!\");", replace: "toast.success(nextVal ? L('🌙 Dark theme applied!', '🌙 ڈارک تھیم لاگو ہو گئی!') : L('☀️ Light theme applied!', '☀️ ہلکی تھیم لاگو ہو گئی!'));" },
    { line: 312, find: "const instStr = teacherObj ? teacherObj.name : 'Faculty';", replace: "const instStr = teacherObj ? teacherObj.name : L('Faculty', 'استاد');" },
    { line: 315, find: "toast.success(`🔔 Class Bell: ${lecture.period} has started!`, {", replace: "toast.success(L(`🔔 Class Bell: ${lecture.period} has started!`, `🔔 کلاس بیل: ${lecture.period} شروع ہو گئی!`), {" },
    { line: 347, find: "toast.success(\"All messages marked as read.\");", replace: "toast.success(L('All messages marked as read.', 'تمام پیغامات پڑھے ہوئے نشان زد ہو گئے۔'));" },
    { line: 353, find: "toast.success(\"Notification history cleared.\");", replace: "toast.success(L('Notification history cleared.', 'اطلاعات کی تاریخ صاف ہو گئی۔'));" },
    { line: 433, find: "toast.success(\"ID Card design saved permanently!\");", replace: "toast.success(L('ID Card design saved permanently!', 'شناختی کارڈ ڈیزائن ہمیشہ کے لیے محفوظ ہو گیا!'));" },
    { line: 436, find: "toast.error(\"Saved locally, but failed to sync with cloud.\");", replace: "toast.error(L('Saved locally, but failed to sync with cloud.', 'مقامی طور پر محفوظ ہو گیا، مگر کلاؤڈ سے سنک نہیں ہو سکا۔'));" },
    { line: 466, find: "return t ? t.name : 'Unknown Faculty';", replace: "return t ? t.name : L('Unknown Faculty', 'نامعلوم استاد');" },
    { line: 520, find: '>Attendance Rate</p>', replace: ">{L('Attendance Rate', 'حاضری کی شرح')}</p>" },
    { line: 523, find: '>Log Summary</p>', replace: ">{L('Log Summary', 'لاگ خلاصہ')}</p>" },
    { line: 539, find: '>Student Portal</p>', replace: ">{L('Student Portal', 'طلبہ پورٹل')}</p>" },
    { line: 600, find: 'aria-label="Close menu"', replace: "aria-label={L('Close menu', 'مینو بند کریں')}" },
    { line: 639, find: "aria-label={isPinned ? 'Unpin' : 'Pin'}", replace: "aria-label={isPinned ? L('Unpin', 'پن ہٹائیں') : L('Pin', 'پن کریں')}" },
    { line: 728, find: 'No Active Class Right Now', replace: "{L('No Active Class Right Now', 'ابھی کوئی کلاس نہیں چل رہی')}" },
    { line: 781, find: '>Campus Broadcaster</span>', replace: ">{L('Campus Broadcaster', 'کیمپس براڈکاسٹر')}</span>" },
    { line: 784, find: '>Mark Read</button>', replace: ">{L('Mark Read', 'پڑھ لیں')}</button>" },
    { line: 796, find: 'No notifications received yet', replace: "{L('No notifications received yet', 'ابھی کوئی اطلاع نہیں آئی')}" },
    { line: 836, find: '>STUDENT ADVISORY</span>', replace: ">{L('STUDENT ADVISORY', 'طلبہ مشورہ')}</span>" },
    { line: 905, find: "? 'Good Job! Your attendance is matching the required collegiate percentage index.'", replace: "? L('Good Job! Your attendance is matching the required collegiate percentage index.', 'شاباش! آپ کی حاضری طلبہ کے لیے مطلوبہ فیصد کے مطابق ہے۔')" },
    { line: 906, find: ": 'Warning: Your attendance is below standard requirements (75%). please attend regular lectures.'}", replace: ": L('Warning: Your attendance is below standard requirements (75%). please attend regular lectures.', 'انتباہ: آپ کی حاضری معیاری شرائط (75%) سے کم ہے۔ باقاعدہ لیکرز میں شرکت کریں۔')}" },
    { line: 924, find: 'Report Card Highlights', replace: "{L('Report Card Highlights', 'رپورٹ کارڈ نمایاں خطوط')}" },
    { line: 965, find: 'Academic Mastery & Subject Progress', replace: "{L('Academic Mastery & Subject Progress', 'تعلیمی مہارت اور مضموزن کی پیش رفت')}" },
    { line: 968, find: 'Analyzing cumulative score percentages across all logged examinations and curriculum blocks.', replace: "{L('Analyzing cumulative score percentages across all logged examinations and curriculum blocks.', 'تمام درج امتحانات اور نصابی حصوں میں فیصد کا تجزیہ۔')}" },
    { line: 972, find: 'Overall Academic Weightage', replace: "{L('Overall Academic Weightage', 'مجموعی تعلیمی وزن')}" },
    { line: 1054, find: 'Academic Performance Trends', replace: "{L('Academic Performance Trends', 'تعلیمی کارکردگی کے رجحانات')}" },
    { line: 1057, find: 'Visualizing normalized percentage scores scored across sequential evaluation cycles.', replace: "{L('Visualizing normalized percentage scores scored across sequential evaluation cycles.', 'مسلسل جانچو کے پیشِ نظر فیصد نتائج کا گراف۔')}" },
  ],
};