/* Phase 2 — StudentDashboard part C (timetable, fees, ID card designer) */
module.exports = {
  'src/components/StudentDashboard.tsx': [
    { line: 1445, find: '>Weekly Subject Schedule</h1>', replace: ">{L('Weekly Subject Schedule', 'ہفتہ وار مضمون شیڈول')}</h1>" },
    { line: 1446, find: '>Inspect weekly blocks, periods, assigned subject sessions, and faculty teachers.</p>', replace: ">{L('Inspect weekly blocks, periods, assigned subject sessions, and faculty teachers.', 'ہفتہ وار اوقات، پیریڈیں، مضامین اور اساتذہ دیکھیں۔')}</p>" },
    { line: 1456, find: 'Weekday', replace: "{L('Weekday', 'دن')}" },
    { line: 1469, find: '{day}', replace: "{L(day, ({ Monday: 'پیر', Tuesday: 'منگل', Wednesday: 'بدھ', Thursday: 'جمعرات', Friday: 'جمعہ', Saturday: 'ہفتہ', Sunday: 'اتوار' } as Record<string, string>)[day] ?? day)}" },
    { line: 1483, find: 'Free Period', replace: "{L('Free Period', 'آزاد پیریڈ')}" },
    { line: 1562, find: 'Academic Fee Passbook', replace: "{L('Academic Fee Passbook', 'تعلیمی فیس پاس بک')}" },
    { line: 1569, find: 'Real-time ledger entries displaying school tuition, other funds, fine accruals, and transaction receipts.', replace: "{L('Real-time ledger entries displaying school tuition, other funds, fine accruals, and transaction receipts.', 'اسکول فیس، دیگر فنڈز، جرمانے اور رسیدوں کا ریئل ٹائم ریکارڈ۔')}" },
    { line: 1576, find: '>Total Billed</p>', replace: ">{L('Total Billed', 'کل بل')}</p>" },
    { line: 1581, find: '>Total Settled</p>', replace: ">{L('Total Settled', 'کل ادا شدہ')}</p>" },
    { line: 1583, find: '>Paid ledger transactions</p>', replace: ">{L('Paid ledger transactions', 'ادا شدہ لین دین')}</p>" },
    { line: 1586, find: '>Pending Tuition</p>', replace: ">{L('Pending Tuition', 'باقی فیس')}</p>" },
    { line: 1588, find: '>Pending installments</p>', replace: ">{L('Pending installments', 'باقی اقساط')}</p>" },
    { line: 1595, find: '>Grand Payable</p>', replace: ">{L('Grand Payable', 'کل قابل ادائیگی')}</p>" },
    { line: 1609, find: 'Monthly Tuition Installments', replace: "{L('Monthly Tuition Installments', 'ماہانہ فیس اقساط')}" },
    { line: 1653, find: 'Other Funds & Fines', replace: "{L('Other Funds & Fines', 'دیگر فنڈز اور جرمانے')}" },
    { line: 1671, find: 'No extra fines or class funds recorded', replace: "{L('No extra fines or class funds recorded', 'کوئی اضافی جرمانہ یا کلاس فنڈ درج نہیں')}" },
    { line: 1698, find: 'Student Identity Designer', replace: "{L('Student Identity Designer', 'طلبہ شناختی ڈیزائنر')}" },
    { line: 1702, find: 'Design Your ID Card', replace: "{L('Design Your ID Card', 'اپنا شناختی کارڈ بنائیں')}" },
    { line: 1705, find: 'Customize your academic identity card with themes and colors.', replace: "{L('Customize your academic identity card with themes and colors.', 'اپنے شناختی کارڈ کو تھیم اور رنگ سے پسند کے مطابق بنائیں۔')}" },
    { line: 1720, find: '>Card Preview</h3>', replace: ">{L('Card Preview', 'کارڈ پیش منظر')}</h3>" },
    { line: 1768, find: '>Student Identity</p>', replace: ">{L('Student Identity', 'طلبہ شناخت')}</p>" },
    { line: 1796, find: 'Design Controls', replace: "{L('Design Controls', 'ڈیزائن کنٹرولز')}" },
    { line: 1802, find: '>Select Theme</label>', replace: ">{L('Select Theme', 'تھیم منتخب کریں')}</label>" },
    { line: 1823, find: '>Accent Color</label>', replace: ">{L('Accent Color', 'اکسنٹ رنگ')}</label>" },
  ],
};