/* Phase 3 — TeacherDashboard batch 10: my attendance (GPS) + my pay / salary slip */
module.exports = {
  'src/components/TeacherDashboard.tsx': [
    { line: 4321, find: ">My Attendance</h1>", replace: ">{L('My Attendance', 'میری حاضری')}</h1>" },
    { line: 4322, find: "GPS Verified Check-in / Check-out — Digital Staff Register", replace: "{L('GPS Verified Check-in / Check-out — Digital Staff Register', 'جی پی ایس تصدیق شدہ حاضری / رخصتی — ڈیجیٹل اسٹاف رجسٹر')}" },
    { line: 4335, find: ">Today · {todayStr}</p>", replace: ">{L('Today', 'آج')} · {todayStr}</p>" },
    { line: 4338, find: ": 'NOT CHECKED IN'}", replace: ": L('NOT CHECKED IN', 'حاضری نہیں لگی')}" },
    { line: 4342, find: ">Check-In</p>", replace: ">{L('Check-In', 'حاضری')}</p>" },
    { line: 4346, find: ">Check-Out</p>", replace: ">{L('Check-Out', 'رخصتی')}</p>" },
    { line: 4350, find: ">School Dist</p>", replace: ">{L('School Dist', 'اسکول فاصلہ')}</p>" },
    { line: 4360, find: "<Fingerprint size={16} /> Check-In", replace: "<Fingerprint size={16} /> {L('Check-In', 'حاضری لگائیں')}" },
    { line: 4367, find: "<LogOut size={16} /> Check-Out", replace: "<LogOut size={16} /> {L('Check-Out', 'رخصتی درج کریں')}" },
    { line: 4371, find: ">Demo GPS (School Location)</span>", replace: ">{L('Demo GPS (School Location)', 'ڈیمو جی پی ایس (اسکول لوکیشن)')}</span>" },
    { line: 4376, find: "School: {schoolLocation.name} · Radius {schoolLocation.radiusMeters} m — check-in sirf school ke andar se hota hai.", replace: "{L('School', 'اسکول')}: {schoolLocation.name} · {L('Radius', 'رداس')} {schoolLocation.radiusMeters} m — {L('check-in works only from inside the school.', 'حاضری صرف اسکول کے اندر سے لگ سکتی ہے۔')}" },
    { line: 4388, find: "[['Present', selfAttSummary.presentDays,", replace: "[[L('Present', 'حاضر'), selfAttSummary.presentDays," },
    { line: 4388, find: "['Late', selfAttSummary.lateDays,", replace: "[L('Late', 'تاخیر'), selfAttSummary.lateDays," },
    { line: 4388, find: "['Absent', selfAttSummary.absentDays,", replace: "[L('Absent', 'غیر حاضر'), selfAttSummary.absentDays," },
    { line: 4388, find: "['Leave', selfAttSummary.leaveDays,", replace: "[L('Leave', 'رخصت'), selfAttSummary.leaveDays," },
    { line: 4388, find: "['Marked', selfAttSummary.totalMarked,", replace: "[L('Marked', 'درج شدہ'), selfAttSummary.totalMarked," },
    { line: 4397, find: "Attendance Calendar — {monthLabel(selfAttYear, selfAttMonthIdx)}", replace: "{L('Attendance Calendar', 'حاضری کیلنڈر')} — {monthLabel(selfAttYear, selfAttMonthIdx)}" },
    { line: 4418, find: ">My Attendance History</h3>", replace: ">{L('My Attendance History', 'میری حاضری کی تاریخ')}</h3>" },
    { line: 4424, find: ">Date</th>", replace: ">{L('Date', 'تاریخ')}</th>" },
    { line: 4425, find: ">Status</th>", replace: ">{L('Status', 'صورتحال')}</th>" },
    { line: 4426, find: ">Check-In</th>", replace: ">{L('Check-In', 'حاضری')}</th>" },
    { line: 4427, find: ">Check-Out</th>", replace: ">{L('Check-Out', 'رخصتی')}</th>" },
    { line: 4428, find: ">School Dist</th>", replace: ">{L('School Dist', 'اسکول فاصلہ')}</th>" },
    { line: 4429, find: ">Source</th>", replace: ">{L('Source', 'ذریعہ')}</th>" },
    { line: 4458, find: ">My Pay & Salary Slip</h1>", replace: ">{L('My Pay & Salary Slip', 'میری تنخواہ و پے سلپ')}</h1>" },
    { line: 4481, find: ">Payslip · {monthLabel(myPayslip.year, myPayslip.month)}</p>", replace: ">{L('Payslip', 'تنخواہ پرچی')} · {monthLabel(myPayslip.year, myPayslip.month)}</p>" },
    { line: 4487, find: "Joined: {salaryHistory.joinDate} · {salaryHistory.tenureYears} Saal {salaryHistory.tenureRemMonths} Mahine", replace: "{L('Joined', 'شمولیت')}: {salaryHistory.joinDate} · {salaryHistory.tenureYears} {L('Saal', 'سال')} {salaryHistory.tenureRemMonths} {L('Mahine', 'ماہ')}" },
    { line: 4489, find: "Since {salaryHistory.startLabel} · {salaryHistory.tenureYears} Saal {salaryHistory.tenureRemMonths} Mahine", replace: "{L('Since', 'سے')} {salaryHistory.startLabel} · {salaryHistory.tenureYears} {L('Saal', 'سال')} {salaryHistory.tenureRemMonths} {L('Mahine', 'ماہ')}" },
    { line: 4494, find: ">Net Payable</p>", replace: ">{L('Net Payable', 'قابل ادائیگی')}</p>" },
    { line: 4497, find: "{myPayslip.paid ? `PAID ${myPayslip.paidDate ? '· ' + myPayslip.paidDate : ''}` : 'PENDING'}", replace: "{myPayslip.paid ? `${L('PAID', 'ادا شدہ')}${myPayslip.paidDate ? ' · ' + myPayslip.paidDate : ''}` : L('PENDING', 'باقی')}" },
    { line: 4503, find: ">Earnings</h3>", replace: ">{L('Earnings', 'آمدنی')}</h3>" },
    { line: 4505, find: ">Base Salary</span>", replace: ">{L('Base Salary', 'بنیادی تنخواہ')}</span>" },
    { line: 4506, find: "Present Bonus ({myPayslip.presentDays} days × {formatPKR(myPayConfig.bonusPerPresentDay)})", replace: "{L('Present Bonus', 'حاضری بونس')} ({myPayslip.presentDays} {L('days', 'دن')} × {formatPKR(myPayConfig.bonusPerPresentDay)})" },
    { line: 4507, find: ">Allowances</span>", replace: ">{L('Allowances', 'الاؤنس')}</span>" },
    { line: 4510, find: ">Total Earnings</span>", replace: ">{L('Total Earnings', 'کل آمدنی')}</span>" },
    { line: 4515, find: ">Deductions</h3>", replace: ">{L('Deductions', 'کٹوتیاں')}</h3>" },
    { line: 4517, find: "Late ({myPayslip.lateDays} day × {formatPKR(myPayConfig.lateDeductionPerDay)})", replace: "{L('Late', 'تاخیر')} ({myPayslip.lateDays} {L('day', 'دن')} × {formatPKR(myPayConfig.lateDeductionPerDay)})" },
    { line: 4518, find: "Absent ({myPayslip.absentDays} day × {formatPKR(myPayConfig.absentDeductionPerDay)})", replace: "{L('Absent', 'غیر حاضر')} ({myPayslip.absentDays} {L('day', 'دن')} × {formatPKR(myPayConfig.absentDeductionPerDay)})" },
    { line: 4519, find: ">Fixed Deductions</span>", replace: ">{L('Fixed Deductions', 'مقررہ کٹوتیاں')}</span>" },
    { line: 4522, find: ">Net Payable</span>", replace: ">{L('Net Payable', 'قابل ادائیگی')}</span>" },
    { line: 4533, find: ">Complete Salary History</h3>", replace: ">{L('Complete Salary History', 'مکمل تنخواہ ریکارڈ')}</h3>" },
    { line: 4540, find: ">Service Tenure</p>", replace: ">{L('Service Tenure', 'خدمت کا عرصہ')}</p>" },
    { line: 4550, find: "{ label: 'Total Earned (Net)',", replace: "{ label: L('Total Earned (Net)', 'کل کمائی (نیٹ)')," },
    { line: 4551, find: "{ label: 'Total Paid',", replace: "{ label: L('Total Paid', 'کل ادا شدہ')," },
    { line: 4552, find: "{ label: 'Pending',", replace: "{ label: L('Pending', 'باقی')," },
    { line: 4553, find: "{ label: 'Avg / Month',", replace: "{ label: L('Avg / Month', 'اوسط / ماہ')," },
  ],
};
