/* Phase 3 — TeacherDashboard batch 1: sync toasts, fee modal, GPS check-in, payslip print */
module.exports = {
  'src/components/TeacherDashboard.tsx': [
    { line: 159, find: "toast.info('Class assignments updated from Principal portal');", replace: "toast.info(L('Class assignments updated from Principal portal', 'پرنسپل پورٹل سے کلاس اسائنمنٹس اپ ڈیٹ ہو گئیں'));" },
    { line: 175, find: "toast.info('Timetable updated from Principal portal');", replace: "toast.info(L('Timetable updated from Principal portal', 'پرنسپل پورٹل سے ٹائم ٹیبل اپ ڈیٹ ہو گیا'));" },
    { line: 255, find: "alert('Please select a student and enter amount.');", replace: "alert(L('Please select a student and enter amount.', 'براہِ کرم طالب علم منتخب کریں اور رقم لکھیں۔'));" },
    { line: 309, find: "toast.success(`Collection of ${collected} for ${student.name} recorded!`);", replace: "toast.success(L(`Collection of ${collected} for ${student.name} recorded!`, `کلیکشن ${collected} برائے ${student.name} درج ہو گئی!`));" },
    { line: 453, find: "note: useDemoPosition ? 'Demo GPS (school location)' : 'Live GPS',", replace: "note: useDemoPosition ? L('Demo GPS (school location)', 'ڈیمو جی پی ایس (اسکول لوکیشن)') : L('Live GPS', 'لائیو جی پی ایس')," },
    { line: 458, find: "title: `Check-in: ${userSession.name}`,", replace: "title: L(`Check-in: ${userSession.name}`, `حاضری: ${userSession.name}`)," },
    { line: 459, find: "message: `${userSession.name} ne ${now.toLocaleTimeString()} par check-in kiya (${isLate ? 'LATE' : 'On Time'}, ${useDemoPosition ? 'Demo GPS' : formatDistance(Math.round(dist || 0))} school se).`,", replace: "message: L(`${userSession.name} checked in at ${now.toLocaleTimeString()} (${isLate ? 'LATE' : 'On Time'}, ${useDemoPosition ? 'Demo GPS' : formatDistance(Math.round(dist || 0))} from school).`, `${userSession.name} نے ${now.toLocaleTimeString()} پر حاضری لگائی (${isLate ? 'تاخیر' : 'بروقت'}, ${useDemoPosition ? 'ڈیمو جی پی ایس' : formatDistance(Math.round(dist || 0))} اسکول سے)۔`)," },
    { line: 626, find: ">Base Salary</td>", replace: ">${L('Base Salary', 'بنیادی تنخواہ')}</td>" },
    { line: 627, find: ">Present Days (${s.presentDays}) × Daily Bonus</td>", replace: ">${L('Present Days', 'حاضری کے دن')} (${s.presentDays}) × ${L('Daily Bonus', 'روزانہ بونس')}</td>" },
    { line: 628, find: ">Allowances</td>", replace: ">${L('Allowances', 'الاؤنس')}</td>" },
    { line: 629, find: ">Late Deduction (${s.lateDays} day)</td>", replace: ">${L('Late Deduction', 'تاخیر کٹوتی')} (${s.lateDays} ${L('day', 'دن')})</td>" },
    { line: 630, find: ">Absent Deduction (${s.absentDays} day)</td>", replace: ">${L('Absent Deduction', 'غیر حاضری کٹوتی')} (${s.absentDays} ${L('day', 'دن')})</td>" },
    { line: 631, find: ">Fixed Deductions</td>", replace: ">${L('Fixed Deductions', 'مقررہ کٹوتیاں')}</td>" },
    { line: 632, find: "<title>Payslip - ${t.name}</title>", replace: "<title>${L('Payslip', 'تنخواہ پرچی')} - ${t.name}</title>" },
    { line: 652, find: ">${t.subject} · Payslip</div>", replace: ">${t.subject} · ${L('Payslip', 'تنخواہ پرچی')}</div>" },
    { line: 653, find: ">Net Payable</div>", replace: ">${L('Net Payable', 'قابل ادائیگی')}</div>" },
    { line: 656, find: "><b>Period</b>", replace: "><b>${L('Period', 'مدت')}</b>" },
    { line: 657, find: "><b>Present</b>", replace: "><b>${L('Present', 'حاضر')}</b>" },
    { line: 658, find: "><b>Late</b>", replace: "><b>${L('Late', 'تاخیر')}</b>" },
    { line: 659, find: "><b>Absent</b>", replace: "><b>${L('Absent', 'غیر حاضر')}</b>" },
    { line: 660, find: "><b>Leave</b>", replace: "><b>${L('Leave', 'رخصت')}</b>" },
    { line: 661, find: "><b>Status</b>${s.paid ? 'PAID' : 'PENDING'}", replace: "><b>${L('Status', 'صورتحال')}</b>${s.paid ? L('PAID', 'ادا شدہ') : L('PENDING', 'باقی')}" },
    { line: 664, find: ">Net Payable</td>", replace: ">${L('Net Payable', 'قابل ادائیگی')}</td>" },
    { line: 665, find: "${schoolName} — Digital Registrar</span>", replace: "${schoolName} — ${L('Digital Registrar', 'ڈیجیٹل رجسٹرار')}</span>" },
    { line: 670, find: "toast.error('Pop-up blocked. Allow pop-ups to print payslip.');", replace: "toast.error(L('Pop-up blocked. Allow pop-ups to print payslip.', 'پاپ اپ بلاک ہو گیا۔ تنخواہ پرچی پرنٹ کرنے کے لیے پاپ اپ کی اجازت دیں۔'));" },
  ],
};
