/* Phase 3 — TeacherDashboard batch 11: fees ledger + security settings form */
module.exports = {
  'src/components/TeacherDashboard.tsx': [
    { line: 4665, find: ">Ledger & Financials</h1>", replace: ">{L('Ledger & Financials', 'کھاتہ و مالیات')}</h1>" },
    { line: 4666, find: "Class Fee Tracking & Collection Status (Digital Registrar)", replace: "{L('Class Fee Tracking & Collection Status (Digital Registrar)', 'کلاس فیس کی نگرانی و وصولی کی صورتحال (ڈیجیٹل رجسٹرار)')}" },
    { line: 4672, find: "Record Cash Collection", replace: "{L('Record Cash Collection', 'نقد وصولی درج کریں')}" },
    { line: 4678, find: ">Total Expected</p>", replace: ">{L('Total Expected', 'کل متوقع')}</p>" },
    { line: 4684, find: ">Cash Collected</p>", replace: ">{L('Cash Collected', 'نقد وصول شدہ')}</p>" },
    { line: 4690, find: ">Pending Dues</p>", replace: ">{L('Pending Dues', 'باقی واجبات')}</p>" },
    { line: 4700, find: "Recent Collection Ledger", replace: "{L('Recent Collection Ledger', 'حالیہ وصولی کا کھاتہ')}" },
    { line: 4707, find: ">Transaction ID</th>", replace: ">{L('Transaction ID', 'ٹرانزیکشن آئی ڈی')}</th>" },
    { line: 4708, find: ">Student Profile</th>", replace: ">{L('Student Profile', 'طالب علم پروفائل')}</th>" },
    { line: 4709, find: ">Date</th>", replace: ">{L('Date', 'تاریخ')}</th>" },
    { line: 4710, find: ">Amount</th>", replace: ">{L('Amount', 'رقم')}</th>" },
    { line: 4711, find: ">Status</th>", replace: ">{L('Status', 'صورتحال')}</th>" },
    { line: 4719, find: "('Roll #' + student.rollNumber)", replace: "(L('Roll #', 'رول نمبر') + ' ' + student.rollNumber)" },
    { line: 4719, find: ": 'Student Record';", replace: ": L('Student Record', 'طالب علم ریکارڈ');" },
    { line: 4730, find: ">Verified</span>", replace: ">{L('Verified', 'تصدیق شدہ')}</span>" },
    { line: 4737, find: "No collection records found in active period", replace: "{L('No collection records found in active period', 'منتخب مدت میں کوئی وصولی ریکارڈ نہیں ملی')}" },
    { line: 4759, find: ">Security & Profile Settings</h2>", replace: ">{L('Security & Profile Settings', 'سیکیورٹی و پروفائل ترتیبات')}</h2>" },
    { line: 4760, find: ">Update your portal login identity and password credentials below.</p>", replace: ">{L('Update your portal login identity and password credentials below.', 'اپنا پورٹل لاگ اِن اور پاس ورڈ نیچے اپ ڈیٹ کریں۔')}</p>" },
    { line: 4773, find: "toast.error(\"ID and Password cannot be empty.\");", replace: "toast.error(L('ID and Password cannot be empty.', 'آئی ڈی اور پاس ورڈ خالی نہیں ہو سکتے۔'));" },
    { line: 4778, find: "toast.error(\"Passwords do not match.\");", replace: "toast.error(L('Passwords do not match.', 'پاس ورڈ آپس میں نہیں ملتے۔'));" },
    { line: 4787, find: "toast.success(\"Profile credentials updated successfully! These changes are now active.\");", replace: "toast.success(L('Profile credentials updated successfully! These changes are now active.', 'پروفائل کی تفصیلات کامیابی سے اپ ڈیٹ ہو گئیں! تبدیلیاں فعال ہیں۔'));" },
    { line: 4793, find: ">Portal Login ID / Username</label>", replace: ">{L('Portal Login ID / Username', 'پورٹل لاگ اِن آئی ڈی / صارف نام')}</label>" },
    { line: 4799, find: "placeholder=\"Enter new login ID\"", replace: "placeholder={L('Enter new login ID', 'نیا لاگ اِن آئی ڈی لکھیں')}" },
    { line: 4805, find: ">New Password</label>", replace: ">{L('New Password', 'نیا پاس ورڈ')}</label>" },
    { line: 4811, find: "placeholder=\"Enter new password\"", replace: "placeholder={L('Enter new password', 'نیا پاس ورڈ لکھیں')}" },
    { line: 4817, find: ">Confirm New Password</label>", replace: ">{L('Confirm New Password', 'نیا پاس ورڈ دوبارہ لکھیں')}</label>" },
    { line: 4822, find: "placeholder=\"Confirm new password\"", replace: "placeholder={L('Confirm new password', 'نیا پاس ورڈ دوبارہ لکھیں')}" },
    { line: 4833, find: "Update Credentials", replace: "{L('Update Credentials', 'لاگ اِن تفصیلات اپ ڈیٹ کریں')}" },
    { line: 4839, find: "Security Notice", replace: "{L('Security Notice', 'سیکیورٹی نوٹس')}" },
  ],
};
