/* Phase 3 — TeacherDashboard batch 7: exam roster, report card builder */
module.exports = {
  'src/components/TeacherDashboard.tsx': [
    { line: 3222, find: ">Configure the Exam First</h3>", replace: ">{L('Configure the Exam First', 'پہلے امتحان ترتیب دیں')}</h3>" },
    { line: 3224, find: "Choose the class, subject and exam name (e.g. 1st Term, 2nd Term, 3rd Term, Annual, Monthly Test) then press Load Roster to begin entering marks.", replace: "{L('Choose the class, subject and exam name (e.g. 1st Term, 2nd Term, 3rd Term, Annual, Monthly Test) then press Load Roster to begin entering marks.', 'کلاس، مضمون اور امتحان کا نام منتخب کریں (مثلاً پہلی، دوسری، تیسری ششماہی، سالانہ، ماہانہ ٹیسٹ) اور پھر نمبر درج کرنے کے لیے \"فہرست لوڈ کریں\" دبائیں۔')}" },
    { line: 3234, find: "{selectedExamType} Marks — {selectedSubject}", replace: "{selectedExamType} {L('Marks', 'نمبر')} — {selectedSubject}" },
    { line: 3237, find: "{examClassStudents.length} Student(s) · Total {maxMarksInput}", replace: "{examClassStudents.length} {L('Student(s)', 'طالب علم')} · {L('Total', 'کل')} {maxMarksInput}" },
    { line: 3245, find: "No students enrolled in this class.", replace: "{L('No students enrolled in this class.', 'اس کلاس میں کوئی طالب علم داخل نہیں۔')}" },
    { line: 3255, find: "Roll #{s.rollNumber}", replace: "{L('Roll #', 'رول نمبر')} {s.rollNumber}" },
    { line: 3260, find: ">Obtained Marks</span>", replace: ">{L('Obtained Marks', 'حاصل کردہ نمبر')}</span>" },
    { line: 3263, find: ">Absent</span>", replace: ">{L('Absent', 'غیر حاضر')}</span>" },
    { line: 3289, find: ">Roll No</th>", replace: ">{L('Roll No', 'رول نمبر')}</th>" },
    { line: 3290, find: ">Student</th>", replace: ">{L('Student', 'طالب علم')}</th>" },
    { line: 3291, find: ">Obtained Marks</th>", replace: ">{L('Obtained Marks', 'حاصل کردہ نمبر')}</th>" },
    { line: 3292, find: ">Total</th>", replace: ">{L('Total', 'کل')}</th>" },
    { line: 3299, find: "No students enrolled in this class.", replace: "{L('No students enrolled in this class.', 'اس کلاس میں کوئی طالب علم داخل نہیں۔')}" },
    { line: 3310, find: ">Absent</span>", replace: ">{L('Absent', 'غیر حاضر')}</span>" },
    { line: 3351, find: ">Student Report Card Builder</h1>", replace: ">{L('Student Report Card Builder', 'طلبہ رپورٹ کارڈ بنائیں')}</h1>" },
    { line: 3357, find: ">Select Class:</span>", replace: ">{L('Select Class', 'کلاس منتخب کریں')}:</span>" },
    { line: 3367, find: ">-- Choose Class --</option>", replace: ">{L('-- Choose Class --', '-- کلاس منتخب کریں --')}</option>" },
    { line: 3376, find: ">Select Student:</span>", replace: ">{L('Select Student', 'طالب علم منتخب کریں')}:</span>" },
    { line: 3382, find: ">-- Choose Student --</option>", replace: ">{L('-- Choose Student --', '-- طالب علم منتخب کریں --')}</option>" },
    { line: 3416, find: ">Report Card For</p>", replace: ">{L('Report Card For', 'رپورٹ کارڈ برائے')}</p>" },
    { line: 3421, find: ">Exam / Assessment Name</label>", replace: ">{L('Exam / Assessment Name', 'امتحان / جانچ کا نام')}</label>" },
    { line: 3426, find: "placeholder=\"e.g. 1st Term 2025\"", replace: "placeholder={L('e.g. 1st Term 2025', 'مثلاً پہلی ششماہی 2025')}" },
    { line: 3436, find: ">Add Subject to Report</h3>", replace: ">{L('Add Subject to Report', 'رپورٹ میں مضمون شامل کریں')}</h3>" },
    { line: 3440, find: ">Active Subject</label>", replace: ">{L('Active Subject', 'فعال مضمون')}</label>" },
    { line: 3447, find: ">Select Subject</option>", replace: ">{L('Select Subject', 'مضمون منتخب کریں')}</option>" },
    { line: 3448, find: ">English</option>", replace: ">{L('English', 'انگریزی')}</option>" },
    { line: 3449, find: ">Mathematics</option>", replace: ">{L('Mathematics', 'ریاضی')}</option>" },
    { line: 3450, find: ">Science</option>", replace: ">{L('Science', 'سائنس')}</option>" },
    { line: 3451, find: ">Urdu</option>", replace: ">{L('Urdu', 'اردو')}</option>" },
    { line: 3452, find: ">Islamiat</option>", replace: ">{L('Islamiat', 'اسلامیات')}</option>" },
    { line: 3453, find: ">Computer</option>", replace: ">{L('Computer', 'کمپیوٹر')}</option>" },
    { line: 3454, find: ">Physics</option>", replace: ">{L('Physics', 'فزکس')}</option>" },
    { line: 3455, find: ">Chemistry</option>", replace: ">{L('Chemistry', 'کیمسٹری')}</option>" },
    { line: 3456, find: ">Biology</option>", replace: ">{L('Biology', 'بیالوجی')}</option>" },
    { line: 3457, find: ">History</option>", replace: ">{L('History', 'تاریخ')}</option>" },
    { line: 3458, find: ">Geography</option>", replace: ">{L('Geography', 'جغرافیہ')}</option>" },
    { line: 3459, find: ">➕ Manual Subject...</option>", replace: ">{L('➕ Manual Subject...', '➕ نیا مضمون...')}</option>" },
    { line: 3467, find: "placeholder=\"Type subject name (e.g. Quran, Art)\"", replace: "placeholder={L('Type subject name (e.g. Quran, Art)', 'مضمون کا نام لکھیں (مثلاً قرآن، آرٹ)')}" },
    { line: 3474, find: "title=\"Back to list\"", replace: "title={L('Back to list', 'فہرست پر واپس')}" },
    { line: 3483, find: ">Book / Test Reference</label>", replace: ">{L('Book / Test Reference', 'کتاب / ٹیسٹ حوالہ')}</label>" },
    { line: 3488, find: "placeholder=\"e.g. Oxford Book Ch 2, Mid Term\"", replace: "placeholder={L('e.g. Oxford Book Ch 2, Mid Term', 'مثلاً آکسفورڈ باب 2، ششماہی')}" },
    { line: 3498, find: "toast.error('Please enter a subject'); return; }", replace: "toast.error(L('Please enter a subject', 'مضمون لکھیں')); return; }" },
    { line: 3509, find: "toast.success('Subject row added below');", replace: "toast.success(L('Subject row added below', 'مضمون کی سطر نیچے شامل ہو گئی'));" },
    { line: 3514, find: "Add subject to Report", replace: "{L('Add subject to Report', 'رپورٹ میں مضمون شامل کریں')}" },
    { line: 3549, find: "Profile", replace: "{L('Profile', 'پروفائل')}" },
    { line: 3560, find: "No student profiles enrolled inside this class register.", replace: "{L('No student profiles enrolled inside this class register.', 'اس کلاس رجسٹر میں کوئی طالب علم درج نہیں۔')}" },
    { line: 3570, find: ">Subject</th>", replace: ">{L('Subject', 'مضمون')}</th>" },
    { line: 3571, find: ">Assessment Reference</th>", replace: ">{L('Assessment Reference', 'جانچ کا حوالہ')}</th>" },
    { line: 3572, find: ">Total Marks</th>", replace: ">{L('Total Marks', 'کل نمبر')}</th>" },
    { line: 3573, find: ">Obtained Marks</th>", replace: ">{L('Obtained Marks', 'حاصل کردہ نمبر')}</th>" },
    { line: 3574, find: ">Action</th>", replace: ">{L('Action', 'کارروائی')}</th>" },
    { line: 3581, find: "No subjects added to this report card yet. Select a subject above and press Add.", replace: "{L('No subjects added to this report card yet. Select a subject above and press Add.', 'اس رپورٹ کارڈ میں ابھی کوئی مضمون شامل نہیں۔ اوپر سے مضمون منتخب کر کے شامل کریں دبائیں۔')}" },
  ],
};
