/* Phase 3 — TeacherDashboard batch 4: Quick Diary card, students roster, attendance views */
module.exports = {
  'src/components/TeacherDashboard.tsx': [
    { line: 2103, find: ">Quick Diary</h3>", replace: ">{L('Quick Diary', 'فوری ڈائری')}</h3>" },
    { line: 2104, find: ">Post an assignment to your class students</p>", replace: ">{L('Post an assignment to your class students', 'اپنی کلاس کے طلبہ کو ہوم ورک دیں')}</p>" },
    { line: 2111, find: "Full Diary", replace: "{L('Full Diary', 'مکمل ڈائری')}" },
    { line: 2118, find: ">Class</label>", replace: ">{L('Class', 'کلاس')}</label>" },
    { line: 2124, find: ">No assigned classes</option>", replace: ">{L('No assigned classes', 'کوئی تفویض شدہ کلاس نہیں')}</option>" },
    { line: 2131, find: ">Subject</label>", replace: ">{L('Subject', 'مضمون')}</label>" },
    { line: 2134, find: "|| 'e.g. Mathematics'}", replace: "|| L('e.g. Mathematics', 'مثلاً ریاضی')}" },
    { line: 2141, find: ">Due Date</label>", replace: ">{L('Due Date', 'آخری تاریخ')}</label>" },
    { line: 2152, find: ">Assignment Title *</label>", replace: ">{L('Assignment Title *', 'ہوم ورک کا عنوان *')}</label>" },
    { line: 2155, find: "placeholder=\"e.g. Chapter 5 Exercise Questions\"", replace: "placeholder={L('e.g. Chapter 5 Exercise Questions', 'مثلاً باب 5 کے مشقی سوالات')}" },
    { line: 2163, find: ">Instructions / Details</label>", replace: ">{L('Instructions / Details', 'ہدایات / تفصیل')}</label>" },
    { line: 2166, find: "placeholder=\"Write the assignment details, page numbers, or submission instructions...\"", replace: "placeholder={L('Write the assignment details, page numbers, or submission instructions...', 'ہوم ورک کی تفصیل، صفحہ نمبر یا جمع کرانے کی ہدایات لکھیں...')}" },
    { line: 2195, find: ">My Students Roster</h1>", replace: ">{L('My Students Roster', 'میرے طلبہ کی فہرست')}</h1>" },
    { line: 2200, find: ">Classroom:</span>", replace: ">{L('Classroom', 'کلاس روم')}:</span>" },
    { line: 2218, find: "Students in {viewClass ?", replace: "{L('Students in', 'طلبہ — کلاس')} {viewClass ?" },
    { line: 2221, find: "} Assigned Pupils", replace: "} {L('Assigned Pupils', 'تفویض شدہ طلبہ')}" },
    { line: 2229, find: ">Roll #</th>", replace: ">{L('Roll #', 'رول نمبر')}</th>" },
    { line: 2230, find: ">Student Name</th>", replace: ">{L('Student Name', 'طالب علم کا نام')}</th>" },
    { line: 2231, find: ">Contact parent Phone</th>", replace: ">{L('Contact parent Phone', 'والدین کا فون')}</th>" },
    { line: 2232, find: ">Actions</th>", replace: ">{L('Actions', 'کارروائیاں')}</th>" },
    { line: 2260, find: "Profile", replace: "{L('Profile', 'پروفائل')}" },
    { line: 2268, find: "No student profiles enrolled inside this class register.", replace: "{L('No student profiles enrolled inside this class register.', 'اس کلاس رجسٹر میں کوئی طالب علم درج نہیں۔')}" },
    { line: 2284, find: ">Mark Daily Attendance</h1>", replace: ">{L('Mark Daily Attendance', 'روزانہ حاضری لگائیں')}</h1>" },
    { line: 2290, find: ">Class:</span>", replace: ">{L('Class', 'کلاس')}:</span>" },
    { line: 2304, find: ">Log Date:</span>", replace: ">{L('Log Date', 'تاریخ')}:</span>" },
    { line: 2327, find: ">🎴 Student Cards Grid</option>", replace: ">{L('🎴 Student Cards Grid', '🎴 طلبہ کارڈ گرڈ')}</option>" },
    { line: 2328, find: ">📋 Spreadsheet List</option>", replace: ">{L('📋 Spreadsheet List', '📋 شیٹ لسٹ')}</option>" },
    { line: 2329, find: ">✨ Swipe Card Mode</option>", replace: ">{L('✨ Swipe Card Mode', '✨ سوائپ کارڈ موڈ')}</option>" },
    { line: 2345, find: ">Batch Mark:</span>", replace: ">{L('Batch Mark', 'اجتماعی حاضری')}:</span>" },
    { line: 2352, find: "toast.success(\"Marked all students as Present\");", replace: "toast.success(L('Marked all students as Present', 'تمام طلبہ کو حاضر لگا دیا گیا'));" },
    { line: 2356, find: "✅ All Present", replace: "✅ {L('All Present', 'سب حاضر')}" },
    { line: 2364, find: "toast.success(\"Marked all students as Absent\");", replace: "toast.success(L('Marked all students as Absent', 'تمام طلبہ کو غیر حاضر لگا دیا گیا'));" },
    { line: 2378, find: "Save & Commit Attendance", replace: "{L('Save & Commit Attendance', 'حاضری محفوظ کریں')}" },
    { line: 2446, find: "{isPaid ? 'Fee Paid' : 'Fee Pending'}", replace: "{isPaid ? L('Fee Paid', 'فیس ادا شدہ') : L('Fee Pending', 'فیس باقی')}" },
    { line: 2467, find: "{st === 'present' ? 'P' : st === 'absent' ? 'A' : st === 'late' ? 'L' : 'LV'}", replace: "{st === 'present' ? L('P', 'ح') : st === 'absent' ? L('A', 'غ') : st === 'late' ? L('L', 'ت') : L('LV', 'ر')}" },
    { line: 2477, find: "No students enrolled in this class group.", replace: "{L('No students enrolled in this class group.', 'اس کلاس گروپ میں کوئی طالب علم نہیں۔')}" },
    { line: 2489, find: "Commit and Save Attendance Logs", replace: "{L('Commit and Save Attendance Logs', 'حاضری کے لاگ محفوظ کریں')}" },
  ],
};
